### ISSUE TITLE
Connect to specific path

### ISSUE THREAD

**Issue by carloscrono** [andrasq/node-qrpc#1]
Hello, I'd like to connect to an specific rpc service path. For example:

host: 'myurl.mine.com',
port: 7001,
path: '/my/webservice'

Is that possible with your library?
The thing is that I need to consume an RPC Service hosted in a JAVA application.

Thanks a lot.

**Comment by andrasq** [comment]
it's unlikely that it would work, the protocols won't match.  Remote connections are always to just host:port, so the `path` is passed as a parameter inside the request and the listener at host:port must extract and act on it.  The above is possibly RPC built on top of HTTP (which has a standard way of passing the path alongside the request payload), not a wire-level RPC like qrpc.

**Comment by carloscrono** [comment]
I undestand.

Thanks anyway.

**Comment by andrasq** [comment]
Sure, thanks for checking.
